version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile-dev
    container_name: ${DOCKER_CONTAINER_NAME}
    ports:
      - "3030:8081"
    volumes:
      - .:/usr/src/app
      - ${HOME}/.aws:/root/.aws
    entrypoint: ["post-launch"]
